// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9gkkRuMMmlfNO4oigJjsZH-gHUay_3w',
    appId: '1:783738348690:web:829160c4da76eb8c00724b',
    messagingSenderId: '783738348690',
    projectId: 'loging-app-63b39',
    authDomain: 'loging-app-63b39.firebaseapp.com',
    storageBucket: 'loging-app-63b39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4TpJ3VowJ5nTHBP5JEDmyLOvsZxgQgk',
    appId: '1:783738348690:android:494a2dbe9f46c47600724b',
    messagingSenderId: '783738348690',
    projectId: 'loging-app-63b39',
    storageBucket: 'loging-app-63b39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt3yAAJrH3VUc7IhDNmUkJ-mFhOw7EcVA',
    appId: '1:783738348690:ios:959319e715a7e27d00724b',
    messagingSenderId: '783738348690',
    projectId: 'loging-app-63b39',
    storageBucket: 'loging-app-63b39.appspot.com',
    iosClientId: '783738348690-ohtdivmpm0j4n19gflt5n4ghu4glctin.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt3yAAJrH3VUc7IhDNmUkJ-mFhOw7EcVA',
    appId: '1:783738348690:ios:24d111ce9d6a5d9100724b',
    messagingSenderId: '783738348690',
    projectId: 'loging-app-63b39',
    storageBucket: 'loging-app-63b39.appspot.com',
    iosClientId: '783738348690-aq2eagq8t5og0u8tuk0k3l1b4l680b4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp.RunnerTests',
  );
}
